# Generated by Django 3.2.7 on 2022-07-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chart_type', models.CharField(choices=[('dividend', 'Dividend'), ('expense', 'Expense'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue')], max_length=10)),
                ('balance', models.FloatField(default=0.0)),
                ('is_cash', models.BooleanField(default=True)),
                ('is_fund', models.BooleanField(default=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin.bin')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher', models.CharField(blank=True, max_length=15, null=True)),
                ('trn_type', models.CharField(blank=True, max_length=15, null=True)),
                ('particular', models.CharField(blank=True, max_length=254, null=True)),
                ('narration', models.CharField(blank=True, max_length=254, null=True)),
                ('debit_amount', models.IntegerField(default=0)),
                ('credit_amount', models.IntegerField(default=0)),
                ('balance', models.FloatField(default=0.0)),
                ('source_doc', models.ImageField(blank=True, null=True, upload_to='images/ledger_docs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin.bin')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.chartofaccount')),
            ],
        ),
    ]
