# Generated by Django 3.2.7 on 2022-08-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bin', '0001_initial'),
        ('account', '0003_auto_20220815_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bin.bin'),
            preserve_default=False,
        ),
    ]
