# Generated by Django 3.2.7 on 2022-09-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_payment_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='check_status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='CheckStatus',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
