# Generated by Django 3.2.7 on 2022-08-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_humanresource_hr_id'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='damaged',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='intake',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('damaged', 'Damaged')], max_length=10)),
                ('input', models.IntegerField(default=0)),
                ('output', models.IntegerField(default=0)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=254, null=True)),
                ('is_company_transection', models.BooleanField(default=False)),
                ('created', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.humanresource')),
            ],
        ),
    ]
