# Generated by Django 3.2.7 on 2022-08-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220811_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttransaction',
            name='input',
        ),
        migrations.RemoveField(
            model_name='producttransaction',
            name='output',
        ),
        migrations.AddField(
            model_name='producttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=10),
        ),
    ]
