# Generated by Django 3.2.7 on 2022-08-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bin', '0001_initial'),
        ('product', '0005_product_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bin.bin'),
        ),
        migrations.AlterField(
            model_name='producttransaction',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
