# Generated by Django 3.2.7 on 2022-07-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin.bin')),
            ],
        ),
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('date_of_join', models.DateField(blank=True, null=True)),
                ('date_of_resign', models.DateField(blank=True, null=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin.bin')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employeeposition')),
            ],
        ),
    ]
