# Generated by Django 3.2.7 on 2022-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanresource',
            name='hr_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
