# Generated by Django 3.2.7 on 2022-08-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bin', '0001_initial'),
        ('order', '0002_auto_20220813_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin.bin', unique=True)),
                ('default_order_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderstatus')),
            ],
        ),
    ]
