# Generated by Django 3.2.7 on 2022-08-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_humanresource_hr_id'),
        ('order', '0004_alter_ordersetting_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='hr.humanresource'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dsr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsr_sr', to='hr.humanresource'),
        ),
        migrations.DeleteModel(
            name='AssignDelivery',
        ),
    ]
