# Generated by Django 3.2.7 on 2022-08-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220814_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersetting',
            name='default_delivery_sheet_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_sheet', to='order.orderstatus'),
        ),
        migrations.AlterField(
            model_name='ordersetting',
            name='default_order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderstatus'),
        ),
    ]
