# Generated by Django 3.2.7 on 2022-08-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bin', '0001_initial'),
        ('order', '0006_auto_20220814_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=254)),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_phone', models.CharField(max_length=11)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bin.bin')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.route')),
            ],
        ),
    ]
