# Generated by Django 3.2.7 on 2022-08-25 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220825_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.outlet'),
        ),
    ]
